runtime: nodejs16

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.7
  min_instances: 1
  max_instances: 5

handlers:
  - url: /.*
    script: auto

env_variables:
  POSTGRES_HOST: ""
  POSTGRES_PORT: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: ""
  FIREBASE_CONFIG: ""