runtime: nodejs

env_variables:
  NODE_ENV: "production"

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.7
  min_instances: 1
  max_instances: 5

handlers:
  - url: /.*
    script: auto

entrypoint: node src/server.js
